export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_USER_AVATAR = "UPDATE_USER_AVATAR";

export const ADD_TRIP = "ADD_TRIP";
export const UPDATE_TRIP = "UPDATE_TRIP";
export const GET_TRIPS = "GET_TRIPS";
export const DELETE_TRIP = "DELETE_TRIP";
export const TRIPS_LOADING = "TRIPS_LOADING";

export const GET_REQUEST = "GET_REQUEST";
export const ADD_REQUEST = "ADD_REQUEST";
export const DELETE_REQUEST = "DELETE_REQUEST";
export const REQUESTS_LOADING = "REQUESTS_LOADING";
export const GET_REQUEST_USER = "GET_REQUEST_USER";
export const GET_REQUEST_TRIP = "GET_REQUEST_TRIP";

export const GET_ERRORS = "GET_ERRORS";